### ISSUE TITLE
Window size not complete

### ISSUE THREAD

**Issue by NeoDrags** [AEGON247/S-I-D-E#1]
I think there is some issue with resizing as in repl it is showing this
![image](https://user-images.githubusercontent.com/60562379/123532700-102fcb80-d72d-11eb-8693-5ff5a3f9b60b.png)

**Comment by AEGON247** [comment]
> I think there is some issue with resizing as in repl it is showing this
> ![image](https://user-images.githubusercontent.com/60562379/123532700-102fcb80-d72d-11eb-8693-5ff5a3f9b60b.png)

Thank you for raising this issue. The team will look into it soon enough

**Comment by NeoDrags** [comment]
Let me check it out on terminal
